export interface Aircraft {
  slug: string
  name: string
  detail: string
  year: number
  fact: string
  image?: string
  mach?: number
  status?: "active" | "legacy" | "retired"
  description?: string
  specs?: { label: string; value: string }[]
}

export const commercialPlanes: Aircraft[] = [
  {
    slug: "boeing-747",
    name: "Boeing 747",
    detail: "Boeing · USA",
    year: 1968,
    fact: "The 'Queen of the Skies' — the first wide-body jet, its iconic hump reshaping air travel. Production ended February 2023 after 1,574 deliveries spanning 54 years.",
    image: "/planes/boeing747.png",
    status: "legacy",
    description:
      "The Boeing 747 was born from an unlikely partnership between Boeing and Pan American World Airways, who needed something far larger than the 707. Chief engineer Joe Sutter led a team of over 4,500 engineers who designed the jet in just 28 months — a pace so relentless the team was nicknamed 'the Incredibles'. The aircraft's signature upper deck hump was originally conceived as a lounge for first-class passengers; only later did it become a flight deck sitting atop a double-lobe fuselage wide enough to carry standard freight containers side by side.\n\nThe 747's high-bypass turbofan engines, led into service by the Pratt & Whitney JT9D, were themselves a technological leap — nearly three times the bypass ratio of contemporary military engines. The wing, spanning over 211 feet on the -400 variant, used a supercritical aerofoil and sophisticated high-lift devices that allowed the aircraft to operate from existing runways despite weighing up to 910,000 lbs at takeoff. Production ended on February 1, 2023, when the final 747-8F was delivered to Atlas Air — closing a 54-year manufacturing run and the longest in widebody history.",
    specs: [
      { label: "Wingspan", value: "211 ft 5 in (64.4 m)" },
      { label: "Length", value: "231 ft 10 in (70.6 m)" },
      { label: "Engines", value: "4× Pratt & Whitney JT9D / GE CF6 / RR RB211 / GEnx" },
      { label: "Thrust (each)", value: "56,750–66,500 lbf (varies by variant)" },
      { label: "Cruise speed", value: "Mach 0.85 (567 mph / 913 km/h)" },
      { label: "Range", value: "7,730 nmi (14,320 km)" },
      { label: "Passengers", value: "416 (3-class) / up to 660 (all-economy)" },
      { label: "Max takeoff weight", value: "910,000 lb (412,775 kg)" },
      { label: "Service ceiling", value: "45,100 ft (13,747 m)" },
    ],
  },
  {
    slug: "airbus-a380",
    name: "Airbus A380",
    detail: "Airbus · Europe",
    year: 2005,
    fact: "The world's largest passenger aircraft with two full passenger decks, capable of carrying over 800 passengers in all-economy configuration.",
    image: "/planes/a380.png",
    status: "legacy",
    description:
      "The Airbus A380 is an engineering monument shaped by an audacious bet: that the future of aviation lay in flying more people per departure, not more flights. Its double-deck, full-length fuselage — with a cross-section of 7.14 m — required Airbus to invent entirely new manufacturing logistics, building sections in factories across Britain, France, Germany, and Spain before shipping them by barge and convoy to Toulouse for final assembly.\n\nRoughly 25% of the airframe is carbon-fibre-reinforced polymer, and the wing box alone uses CFRP for the first time on a commercial aircraft at this scale. The supercritical wing, spanning nearly 80 metres, is so efficient that the A380 burns just 3.1 litres of fuel per 100 passenger-kilometres — less than a family car. Each of its four Trent 900 or GP7200 engines produces up to 76,500 lbf of thrust, yet the aircraft is certified for noise-sensitive airports because its twin-deck boarding empties passengers faster, reducing block time.",
    specs: [
      { label: "Wingspan", value: "261 ft 8 in (79.75 m)" },
      { label: "Length", value: "238 ft 7 in (72.72 m)" },
      { label: "Height", value: "79 ft (24.09 m)" },
      { label: "Engines", value: "4× Rolls-Royce Trent 900 or Engine Alliance GP7200" },
      { label: "Thrust (each)", value: "70,000–76,500 lbf" },
      { label: "Cruise speed", value: "Mach 0.85 (561 mph / 903 km/h)" },
      { label: "Range", value: "8,000 nmi (14,800 km)" },
      { label: "Passengers", value: "525 (typical 3-class) / 853 (maximum)" },
      { label: "Max takeoff weight", value: "1,268,000 lb (575,000 kg)" },
      { label: "Fuel efficiency", value: "3.1 L / 100 pax-km" },
    ],
  },
  {
    slug: "concorde",
    name: "Concorde",
    detail: "Aérospatiale/BAC · UK & France",
    year: 1969,
    fact: "The only supersonic passenger jet in commercial service. Crossed the Atlantic in under 3.5 hours at Mach 2 — twice the speed of sound.",
    image: "/planes/concorde.png",
    status: "retired",
    description:
      "Concorde was not merely fast — it was a complete reimagining of what a passenger aircraft could be. Its ogival delta wing had no separate tailplane; instead, the entire wing-body generated lift and stability through complex vortex aerodynamics that worked best above Mach 1.3. This forced the aircraft to take off and land at unusually high angles of attack, giving crews the distinctive 'droop-nose' mechanism that lowered the nose section so pilots could actually see the runway.\n\nThe airframe was constructed primarily from aluminium alloy — specifically an alloy developed for aero-engine pistons, because at cruise the skin temperature reached 127°C and the nose tip hit 180°C. Titanium was used only where unavoidable, because its cost and weight would have been prohibitive across the entire fuselage. The four Olympus 593 engines used reheat (afterburner) during takeoff and the transonic acceleration to Mach 1, but cruised supersonically in dry power — the only commercial aircraft ever to do so economically. Each flight consumed roughly 25,000 litres of fuel while carrying just 100 passengers.",
    specs: [
      { label: "Wingspan", value: "83 ft 10 in (25.6 m)" },
      { label: "Length", value: "202 ft 4 in (61.66 m)" },
      { label: "Engines", value: "4× Rolls-Royce/Snecma Olympus 593 Mk 610" },
      { label: "Thrust (each)", value: "38,050 lbf (169.3 kN) with reheat" },
      { label: "Cruise speed", value: "Mach 2.04 (1,354 mph / 2,179 km/h)" },
      { label: "Cruise altitude", value: "60,000 ft (18,300 m)" },
      { label: "Range", value: "3,900 nmi (7,223 km)" },
      { label: "Passengers", value: "92–128" },
      { label: "Max takeoff weight", value: "408,000 lb (185,065 kg)" },
      { label: "Skin temperature at cruise", value: "up to 180°C (nose tip)" },
    ],
  },
  {
    slug: "boeing-777",
    name: "Boeing 777",
    detail: "Boeing · USA",
    year: 1994,
    fact: "The world's largest twin-engine airliner. Its GE90-115B engine holds the verified record for the highest thrust ever produced by a commercial jet engine.",
    description:
      "The Boeing 777 was the first commercial aircraft designed entirely on computer — no paper drawings, no physical mock-up. Eight major airlines co-designed it with Boeing under a 'Working Together' programme that meant the first 777-200 to roll off the line in 1994 fit together perfectly on the first attempt. Its fly-by-wire primary flight computers were the first used by a Boeing airliner, though Boeing retained conventional yoke controls rather than adopting Airbus's side-stick approach.\n\nThe 777's most extraordinary feature is its engine. The GE90-115B's fan blades — 22 of them, each over four feet long — are carbon-fibre composites curved like an eagle's wing and larger than the engines of an entire 737. At 128 inches in diameter, the fan is wider than the fuselage of the 737. In testing it produced 127,900 lbf, setting a world record. The -300ER variant's range of 7,370 nautical miles, combined with its 396-seat capacity, made it the backbone of long-haul international aviation for two decades.",
    specs: [
      { label: "Wingspan", value: "212 ft 7 in (64.8 m)" },
      { label: "Length", value: "242 ft 4 in (73.86 m) — 777-300ER" },
      { label: "Engines", value: "2× General Electric GE90" },
      { label: "Thrust (each)", value: "Up to 115,000 lbf (GE90-115B)" },
      { label: "Cruise speed", value: "Mach 0.84 (554 mph / 892 km/h)" },
      { label: "Range", value: "8,555 nmi (15,844 km) — 777-200LR" },
      { label: "Passengers", value: "396 (2-class, 777-300ER)" },
      { label: "Max takeoff weight", value: "775,000 lb (351,534 kg)" },
      { label: "Service ceiling", value: "43,100 ft (13,137 m)" },
    ],
  },
  {
    slug: "boeing-787-dreamliner",
    name: "Boeing 787 Dreamliner",
    detail: "Boeing · USA",
    year: 2009,
    fact: "First commercial aircraft with over 50% composite materials. Cabin humidity is higher and cabin altitude is lower than any previous jet, reducing passenger fatigue.",
    description:
      "The 787 Dreamliner was Boeing's most radical departure from conventional aluminium construction since the 707. Its fuselage is built from continuous barrel sections of carbon-fibre-reinforced polymer — a one-piece tube rather than thousands of panels and rivets. By weight, the airframe is 50% composite, 20% aluminium, 15% titanium, and 10% steel, making it the first commercial jet in which composites are the dominant structural material.\n\nThe implications cascade through the entire design. Because CFRP doesn't corrode, Boeing could increase cabin humidity from the typical 4% to 15% and lower the equivalent cabin altitude from 8,000 ft to 6,000 ft — measurably reducing headaches and jet lag for passengers. The electrical architecture replaced traditional bleed-air systems (which tap hot compressed air from the engines to power the cabin and de-icing) with an all-electric equivalent, reducing fuel burn. The GEnx and Trent 1000 engines, both geared or three-spool designs, deliver 20% better fuel efficiency than the 767 they replaced.",
    specs: [
      { label: "Wingspan", value: "197 ft 3 in (60.12 m) — 787-8" },
      { label: "Length", value: "186 ft 1 in (56.7 m) — 787-8 / 206 ft 1 in — 787-9" },
      { label: "Engines", value: "2× GE GEnx-1B or Rolls-Royce Trent 1000" },
      { label: "Thrust (each)", value: "64,000–74,100 lbf" },
      { label: "Cruise speed", value: "Mach 0.85 (567 mph / 903 km/h)" },
      { label: "Range", value: "7,635 nmi (14,140 km) — 787-8" },
      { label: "Passengers", value: "242 (2-class, 787-8)" },
      { label: "Max takeoff weight", value: "502,500 lb (227,930 kg) — 787-8" },
      { label: "Composite content", value: "50% by weight" },
      { label: "Cabin altitude", value: "6,000 ft (vs 8,000 ft industry standard)" },
    ],
  },
  {
    slug: "airbus-a350",
    name: "Airbus A350",
    detail: "Airbus · Europe",
    year: 2013,
    fact: "Curved titanium wingtips and a carbon-fibre fuselage achieve 25% better fuel efficiency versus the aircraft it replaces.",
    description:
      "The Airbus A350 XWB ('Extra Wide Body') was conceived after Boeing launched the 787, and Airbus's initial response — simply upgrading the A330 — was rejected so emphatically by airlines that Airbus had to start from scratch. The result exceeds the 787 in composite content: 53% of the A350's structure is CFRP, including not only the wing and tail but the fuselage frames and skin panels. The wider fuselage cross-section, at 5.97 metres, gives passengers noticeably more room than the 787.\n\nThe wing is a masterpiece of aerodynamic engineering. At 64.75 metres, it uses a carbon composite torsion box that allows it to flex several metres at the tip — impossible in aluminium — and terminates in blade-like curved winglets that are integrated into the wing structure rather than bolted on. Each Trent XWB engine produces up to 97,000 lbf, giving the A350-1000 enough thrust to fly the world's longest scheduled route: Singapore to New York, 9,537 nautical miles, 18 hours, 45 minutes.",
    specs: [
      { label: "Wingspan", value: "212 ft 5 in (64.75 m)" },
      { label: "Length", value: "219 ft 2 in (66.8 m) — A350-900" },
      { label: "Engines", value: "2× Rolls-Royce Trent XWB-84 or XWB-97" },
      { label: "Thrust (each)", value: "84,000–97,000 lbf" },
      { label: "Cruise speed", value: "Mach 0.85 (567 mph / 903 km/h)" },
      { label: "Range", value: "8,100 nmi (15,000 km) — A350-900" },
      { label: "Passengers", value: "315–440 (2-class)" },
      { label: "Max takeoff weight", value: "617,300 lb (280,000 kg) — A350-900" },
      { label: "Composite content", value: "53% by weight (more than any other airliner)" },
    ],
  },
  {
    slug: "airbus-a320",
    name: "Airbus A320",
    detail: "Airbus · Europe",
    year: 1987,
    status: "legacy",
    fact: "First airliner with fly-by-wire and side-stick controllers. The A320 family remains the world's best-selling narrowbody jet with over 10,000 in service.",
    description:
      "The Airbus A320 didn't just introduce fly-by-wire to commercial aviation — it introduced an entirely new philosophy of the relationship between pilot and machine. Where Boeing's systems respond directly to pilot inputs, the A320's flight computers enforce a flight envelope: no matter what the pilot commands, the aircraft will never exceed its structural or aerodynamic limits. This 'envelope protection' was controversial at launch and remains debated, but it has made the A320 family one of the safest narrowbodies ever built.\n\nThe side-stick replacing the traditional centre yoke freed up the instrument panel and gave crews more space. The aircraft's cross-section, wider than the Boeing 737, allowed true two-by-three seating with an aisle wide enough to pass a meal trolley. The CFM56 or IAE V2500 engines were more efficient than anything previously fitted to a narrowbody. Over 10,000 A320-family aircraft have been delivered, making it the most successful commercial aircraft programme in history by orders.",
    specs: [
      { label: "Wingspan", value: "117 ft 5 in (35.8 m)" },
      { label: "Length", value: "123 ft 3 in (37.57 m)" },
      { label: "Engines", value: "2× CFM56-5B or IAE V2500" },
      { label: "Thrust (each)", value: "22,000–27,000 lbf" },
      { label: "Cruise speed", value: "Mach 0.78 (514 mph / 828 km/h)" },
      { label: "Range", value: "3,300 nmi (6,150 km)" },
      { label: "Passengers", value: "150–186 (typical / maximum)" },
      { label: "Max takeoff weight", value: "162,040 lb (73,500 kg)" },
      { label: "First fly-by-wire airliner", value: "Yes — side-stick controls, envelope protection" },
    ],
  },
  {
    slug: "airbus-a320neo",
    name: "Airbus A320neo",
    detail: "Airbus · Europe",
    year: 2016,
    fact: "The 'New Engine Option' narrowbody that outsold its Boeing rival before it flew. Over 8,000 orders placed by entry into service — the fastest-selling airliner in history.",
    description:
      "The A320neo (New Engine Option) is precisely what its name says: the A320 family re-engined, rather than redesigned. Airlines could choose between the CFM LEAP-1A or the Pratt & Whitney PW1100G Geared Turbofan — the first time a narrowbody had launched with two competing next-generation engine options. Both deliver around 20% better fuel burn than the CFM56 and V2500 they replace. The GTF achieves this through a reduction gearbox separating the fan and low-pressure turbine, allowing each to spin at its optimal speed — a fundamentally different approach from the LEAP's direct-drive architecture.\n\nBeyond the engine, the A320neo introduced Sharklet wingtip devices — upswept blended winglets that cut induced drag by up to 4% and add 100 nautical miles of range. Because the airframe was otherwise unchanged, A320ceo-rated pilots could fly the neo after a brief differences course. This commonality, combined with the A320's existing advantage in cabin width and automation, allowed Airbus to accumulate over 8,000 neo-family orders before the aircraft entered commercial service with Lufthansa in January 2016 — a milestone that signalled the neo had decisively won the first round of the narrowbody re-engine war.",
    specs: [
      { label: "Wingspan", value: "117 ft 5 in (35.8 m)" },
      { label: "Length", value: "123 ft 3 in (37.57 m) — A320neo" },
      { label: "Engines", value: "CFM LEAP-1A or Pratt & Whitney PW1100G-JM" },
      { label: "Thrust (each)", value: "27,000–32,900 lbf" },
      { label: "Bypass ratio", value: "11:1 (LEAP-1A) / 12:1 (PW1100G)" },
      { label: "Cruise speed", value: "Mach 0.78 (514 mph / 828 km/h)" },
      { label: "Range", value: "3,400–3,800 nmi (depending on variant)" },
      { label: "Passengers", value: "150–194 (2-class to max)" },
      { label: "Max takeoff weight", value: "174,165 lb (79,000 kg)" },
      { label: "Fuel saving vs ceo", value: "~20% per seat" },
    ],
  },
  {
    slug: "embraer-e195-e2",
    name: "Embraer E195-E2",
    detail: "Embraer · Brazil",
    year: 2018,
    fact: "The 'Profit Hunter' — geared turbofan engines and an all-new wing make it the most efficient aircraft in the regional jet category.",
    description:
      "The E195-E2 is the flagship of Embraer's second-generation E-Jet family, and it represents a complete reengineering rather than a modest update. The wing was redesigned from scratch with a new high-aspect-ratio planform and advanced aerofoil sections, reducing drag significantly. The fly-by-wire system — new to the E2 series — allowed the horizontal tail to be made 15% smaller, cutting drag further. The resulting aircraft burns 17.3% less fuel per seat than the original E195.\n\nThe Pratt & Whitney PW1900G 'Geared Turbofan' engine is the core innovation. By inserting a reduction gearbox between the fan and the low-pressure turbine, the fan can spin at its aerodynamically ideal speed while the turbine spins at its mechanically ideal (much faster) speed — something previously impossible. The result is 11% better fuel burn from the engine alone, with a bypass ratio of 12:1 that also makes the E195-E2 dramatically quieter. In a 2-2 all-economy layout, every passenger gets a window or aisle seat — no middle seat on any row.",
    specs: [
      { label: "Wingspan", value: "114 ft 1 in (34.76 m)" },
      { label: "Length", value: "131 ft 4 in (40.04 m)" },
      { label: "Engines", value: "2× Pratt & Whitney PW1900G (Geared Turbofan)" },
      { label: "Thrust (each)", value: "~22,000 lbf" },
      { label: "Bypass ratio", value: "12:1" },
      { label: "Cruise speed", value: "Mach 0.82 (541 mph / 871 km/h)" },
      { label: "Range", value: "2,600 nmi (4,815 km)" },
      { label: "Passengers", value: "120–146 (2-2 seating, no middle seats)" },
      { label: "Max takeoff weight", value: "136,200 lb (61,800 kg)" },
    ],
  },
  {
    slug: "boeing-737",
    name: "Boeing 737",
    detail: "Boeing · USA",
    year: 1967,
    status: "legacy",
    fact: "The best-selling commercial jet in history with over 10,000 delivered. More 737s are in the air at any given moment than any other aircraft type.",
    description:
      "The Boeing 737 began life as a quick, cheap competitor to the Douglas DC-9 — a short-range narrowbody that could use the same 707 cockpit panels and fuselage cross-section to keep development costs down. Its unusual low-slung engine placement, with pods sitting ahead of and below the wing rather than hanging beneath it, was dictated by the aircraft's low ground clearance; a design compromise that has shaped every variant for six decades.\n\nThe 737 has survived through constant reinvention. The 'Classic' series in the 1980s added CFM56 turbofans. The 'Next Generation' series in the 1990s added a new wing, winglets, and a glass cockpit. The MAX, launched in 2011, added the larger LEAP-1B engine — whose size forced further changes to the nose gear and engine mounting that contributed to the MCAS software controversy of 2018. Despite that crisis, the 737 family has accumulated over 15,000 orders across its lifetime, a number no other commercial aircraft has come close to matching.",
    specs: [
      { label: "Wingspan", value: "117 ft 10 in (35.9 m) — 737-800" },
      { label: "Length", value: "129 ft 6 in (39.5 m) — 737-800" },
      { label: "Engines", value: "2× CFM56-7B (NG) or CFM LEAP-1B (MAX)" },
      { label: "Thrust (each)", value: "27,300 lbf (NG) / up to 28,000 lbf (MAX)" },
      { label: "Cruise speed", value: "Mach 0.785 (514 mph / 828 km/h)" },
      { label: "Range", value: "3,115 nmi (5,765 km) — 737-800" },
      { label: "Passengers", value: "162–189 (737-800, 2-class)" },
      { label: "Max takeoff weight", value: "174,200 lb (79,016 kg) — 737-800" },
      { label: "Total orders", value: "Over 15,000 (all variants)" },
    ],
  },
  {
    slug: "boeing-737-max",
    name: "Boeing 737 MAX",
    detail: "Boeing · USA",
    year: 2017,
    fact: "The most controversial commercial jet of the 21st century. Grounded for 20 months after two fatal crashes linked to MCAS software. Recertified in 2020 with hundreds of system changes.",
    description:
      "The 737 MAX began as Boeing's response to Airbus's A320neo — a re-engined narrowbody that airlines could order without retraining pilots or rebuilding maintenance programmes. Boeing chose the CFM LEAP-1B engine, whose 69-inch fan diameter was larger than anything previously fitted to a 737. Because the original 737 sits low to the ground — a legacy of the 1960s design for quick ground turnaround — the LEAP-1B had to be mounted further forward and higher on the wing, shifting the centre of thrust and creating a nose-up pitching tendency at high angles of attack.\n\nTo correct this tendency without requiring pilots to retrain on a 'new' aircraft type, Boeing's engineers developed the Maneuvering Characteristics Augmentation System (MCAS). MCAS used a single angle-of-attack sensor to automatically push the nose down if it sensed the aircraft pitching up excessively. When faulty sensor readings activated MCAS erroneously on Lion Air Flight 610 (October 2018) and Ethiopian Airlines Flight 302 (March 2019), crews were unable to override the repeated nose-down commands. All 346 people across both flights were killed. The MAX was grounded globally for 20 months — the longest grounding of any jet airliner — returning to service in November 2020 after MCAS was redesigned to use dual sensors, with pilot override capability and revised training requirements.",
    specs: [
      { label: "Wingspan", value: "117 ft 10 in (35.9 m)" },
      { label: "Length", value: "138 ft 4 in (42.16 m) — MAX 8" },
      { label: "Engines", value: "2× CFM International LEAP-1B" },
      { label: "Fan diameter", value: "69 in (175 cm) — largest ever on a 737" },
      { label: "Thrust (each)", value: "24,000–28,000 lbf" },
      { label: "Bypass ratio", value: "9:1" },
      { label: "Cruise speed", value: "Mach 0.79 (521 mph / 839 km/h)" },
      { label: "Range", value: "3,550 nmi (6,570 km) — MAX 8" },
      { label: "Passengers", value: "162–178 (MAX 8, typical 2-class)" },
      { label: "Max takeoff weight", value: "181,200 lb (82,191 kg) — MAX 8" },
    ],
  },
  {
    slug: "boeing-757",
    name: "Boeing 757",
    detail: "Boeing · USA",
    year: 1982,
    status: "retired",
    fact: "The narrowbody that could do a widebody's job. Its exceptional thrust-to-weight ratio made it the only single-aisle jet certified for ETOPS transoceanic routes.",
    description:
      "The Boeing 757 was designed alongside the 767 with a shared cockpit philosophy so that pilots could be rated on both aircraft simultaneously — a commercial first. Despite its narrow single-aisle fuselage, it was powered by the same class of engine as wide-body jets: the Rolls-Royce RB211 or Pratt & Whitney PW2000, both producing over 40,000 lbf of thrust. For an aircraft seating 200 passengers, this was extraordinary — a thrust-to-weight ratio that made the 757 one of the most agile commercial jets ever certified.\n\nThat power enabled the 757 to climb steeply from short, high-altitude airports — making it the aircraft of choice for routes like London to Denver, La Paz, and ETOPS transoceanic crossings normally reserved for widebodies. Its 2,000 sq ft supercritical wing provided low drag at high speed. When Boeing discontinued it in 2004, airlines discovered that no aircraft in production could replicate the 757's combination of range, payload, and short-field capability — a capability gap that persists to this day.",
    specs: [
      { label: "Wingspan", value: "124 ft 10 in (38.05 m)" },
      { label: "Length", value: "155 ft 3 in (47.32 m) — 757-200" },
      { label: "Engines", value: "2× Rolls-Royce RB211-535E4B or Pratt & Whitney PW2040" },
      { label: "Thrust (each)", value: "40,100–43,500 lbf" },
      { label: "Cruise speed", value: "Mach 0.80 (528 mph / 850 km/h)" },
      { label: "Range", value: "3,915 nmi (7,250 km)" },
      { label: "Passengers", value: "200 (2-class) / 239 (all-economy)" },
      { label: "Max takeoff weight", value: "255,000 lb (115,666 kg)" },
      { label: "ETOPS rating", value: "ETOPS-180 certified" },
    ],
  },
  {
    slug: "airbus-a330",
    name: "Airbus A330",
    detail: "Airbus · Europe",
    year: 1992,
    fact: "The workhorse of long-haul aviation. Shares 95% commonality with the A340, allowing pilots to fly both types on a single licence — slashing airline training costs.",
    description:
      "The Airbus A330 and A340 were developed simultaneously on a shared airframe — the same fuselage, wing, and systems mated to two or four engines respectively. This 'twinning' strategy let Airbus offer airlines a choice of powerplant philosophy without retraining pilots or restructuring maintenance operations. The A330's wide-body twin-engine design benefited from advances in ETOPS certification that made transoceanic twin-engine operations routine by the early 1990s.\n\nThe fly-by-wire flight control system, shared with the A320 family, gave the A330 envelope protection and automated optimisation of the centre of gravity by transferring fuel between tanks during cruise — automatically improving fuel efficiency without crew input. The aircraft's General Electric CF6, Pratt & Whitney PW4000, or Rolls-Royce Trent 700 engines each produce up to 72,000 lbf, giving the -200 variant sufficient range to serve transpacific sectors. The A330neo, launched in 2014 with Trent 7000 engines, extended the design's life by another generation.",
    specs: [
      { label: "Wingspan", value: "197 ft 10 in (60.3 m)" },
      { label: "Length", value: "208 ft 11 in (63.69 m) — A330-300" },
      { label: "Engines", value: "2× GE CF6-80E1, P&W PW4000, or RR Trent 700/7000" },
      { label: "Thrust (each)", value: "67,500–72,000 lbf" },
      { label: "Cruise speed", value: "Mach 0.82 (541 mph / 871 km/h)" },
      { label: "Range", value: "5,850 nmi (10,800 km) — A330-300" },
      { label: "Passengers", value: "277–335 (2-class)" },
      { label: "Max takeoff weight", value: "513,000 lb (233,000 kg)" },
    ],
  },
  {
    slug: "boeing-707",
    name: "Boeing 707",
    detail: "Boeing · USA",
    year: 1957,
    status: "retired",
    fact: "The jet that started it all. The 707 made transatlantic air travel viable for ordinary passengers, cutting the New York–London crossing from days to hours.",
    description:
      "The Boeing 707 was born from a calculated gamble. Boeing spent $16 million of its own money — a colossal sum in 1952 — building the 367-80 demonstrator to prove the concept of a jet-powered transport and tanker. The gamble worked: the Air Force bought the KC-135 tanker, and the commercial 707 followed. Pan American launched the transatlantic jet era on October 4, 1958, cutting the New York–London crossing from nearly 14 hours by piston airliner to 8 hours.\n\nThe 707's 35-degree swept wing was derived directly from German wartime aerodynamic research and represented a near-perfect balance between high-speed cruise efficiency and acceptable low-speed handling. Its JT3D turbofan engines, replacing earlier pure-jet variants, established the high-bypass principle that all subsequent commercial jets have followed. In military hands, the 707 airframe became the E-3 Sentry AWACS aircraft and the E-8 JSTARS — versions of which are still flying today.",
    specs: [
      { label: "Wingspan", value: "145 ft 9 in (44.4 m)" },
      { label: "Length", value: "152 ft 11 in (46.61 m)" },
      { label: "Engines", value: "4× Pratt & Whitney JT3D turbofan" },
      { label: "Thrust (each)", value: "18,000 lbf (80 kN)" },
      { label: "Cruise speed", value: "Mach 0.86 (567 mph / 912 km/h)" },
      { label: "Range", value: "up to 5,765 nmi (10,676 km)" },
      { label: "Passengers", value: "140–189" },
      { label: "Max takeoff weight", value: "336,000 lb (152,407 kg)" },
      { label: "Service ceiling", value: "42,000 ft (12,802 m)" },
    ],
  },
  {
    slug: "airbus-a220",
    name: "Airbus A220",
    detail: "Airbus / Bombardier · Canada",
    year: 2016,
    fact: "Originally the Bombardier C Series — acquired by Airbus after a trade dispute. Its advanced wing and geared turbofan make it 20% more efficient than jets it replaces.",
    description:
      "The aircraft that became the A220 was designed by Bombardier at the turn of the millennium to fill a specific gap: a jet in the 100–150-seat range built from modern materials and powered by next-generation engines, rather than a shrunken version of a larger plane. The result was the C Series — a clean-sheet design in CFRP and aluminium-lithium alloys with a wing optimised exclusively for this aircraft size, and Pratt & Whitney's new PW1500G Geared Turbofan.\n\nThe aircraft's commercial history became as dramatic as its engineering. Boeing lobbied the US government to impose a 300% tariff on C Series sales to Delta Air Lines, alleging Canadian subsidies constituted unfair competition. Bombardier's response was to give Airbus a majority stake for free — turning the tables completely. Airbus's commercial network then drove orders that Bombardier had been unable to close, and the A220 now competes directly against the 737-7 and A319neo with a structural fuel-burn advantage that Boeing has no direct answer to.",
    specs: [
      { label: "Wingspan", value: "115 ft 5 in (35.1 m)" },
      { label: "Length", value: "127 ft 7 in (38.9 m) — A220-300" },
      { label: "Engines", value: "2× Pratt & Whitney PW1500G (Geared Turbofan)" },
      { label: "Thrust (each)", value: "~23,300 lbf" },
      { label: "Bypass ratio", value: "12:1" },
      { label: "Cruise speed", value: "Mach 0.82 (541 mph / 871 km/h)" },
      { label: "Range", value: "3,400 nmi (6,300 km) — A220-300" },
      { label: "Passengers", value: "130–160 (A220-300)" },
      { label: "Max takeoff weight", value: "149,900 lb (68,000 kg) — A220-300" },
    ],
  },
  {
    slug: "douglas-dc-3",
    name: "Douglas DC-3",
    detail: "Douglas Aircraft · USA",
    year: 1935,
    status: "retired",
    fact: "The aircraft that made airlines profitable. By 1939 the DC-3 carried 90% of the world's airline traffic — and thousands still fly commercially today, nearly 90 years on.",
    description:
      "The Douglas DC-3 emerged from a request by American Airlines for a sleeper aircraft — one with proper berths so passengers could rest on overnight transcontinental flights. Douglas lengthened and widened the DC-2 to accommodate 14 sleeping berths, then discovered that a 21-seat daytime configuration was simply the most economical aircraft ever built for short- and medium-haul routes. Airlines could for the first time turn a profit carrying passengers alone, without mail subsidies.\n\nIts engineering was advanced for its era: all-metal stressed-skin construction, retractable undercarriage, trailing-edge flaps, and a smooth flush-riveted skin were all features that had existed separately on other aircraft but never combined in one design. The two 1,200 hp Wright R-1820 radial engines were reliable enough to sustain single-engine flight fully loaded. In wartime service as the C-47 'Skytrain', it dropped paratroops at Normandy, supplied the Hump route over the Himalayas, and served with every major Allied air force. Roughly 400 remain airworthy today.",
    specs: [
      { label: "Wingspan", value: "95 ft 0 in (28.96 m)" },
      { label: "Length", value: "64 ft 6 in (19.66 m)" },
      { label: "Engines", value: "2× Wright R-1820-202 Cyclone radials" },
      { label: "Power (each)", value: "1,200 hp (895 kW)" },
      { label: "Cruise speed", value: "207 mph (333 km/h)" },
      { label: "Range", value: "1,500 mi (2,400 km)" },
      { label: "Passengers", value: "21–32 (day) / 14 sleeping berths" },
      { label: "Max takeoff weight", value: "25,200 lb (11,431 kg)" },
      { label: "Still airworthy today", value: "~400 aircraft" },
    ],
  },
  {
    slug: "boeing-727",
    name: "Boeing 727",
    detail: "Boeing · USA",
    year: 1963,
    status: "retired",
    fact: "The first jetliner to carry 100 million passengers. Its three rear-mounted engines and high-lift wing allowed operations from shorter runways that widened access to air travel.",
    description:
      "The Boeing 727 was designed to solve a specific operational problem: how to carry jets to smaller airports with shorter runways that were not served by the 707. The solution was radical — three rear-mounted Pratt & Whitney JT8D engines feeding through an S-duct in the tail, eliminating the wing-mounted nacelles that were causing runway clearance issues at the time. This clean-wing configuration also enabled Boeing to fit an extraordinarily powerful high-lift system: triple-slotted flaps occupying most of the trailing edge and Krueger flaps along the leading edge, giving the 727 an approach speed similar to a piston airliner despite its weight.\n\nThe 727 was the first jet to achieve true short-field operations, operating from airports as limited as 4,000 feet. Its T-tail configuration, while creating the risk of 'deep stall' at extreme angles, was necessary to keep the rear engine pods away from the elevators. At peak production, one 727 rolled off the Renton assembly line every working day. It was the first commercial jet to carry 100 million passengers, a milestone it reached in 1982.",
    specs: [
      { label: "Wingspan", value: "108 ft 0 in (32.92 m)" },
      { label: "Length", value: "153 ft 2 in (46.69 m) — 727-200" },
      { label: "Engines", value: "3× Pratt & Whitney JT8D (rear-mounted, one via S-duct)" },
      { label: "Thrust (each)", value: "14,000–16,900 lbf" },
      { label: "Cruise speed", value: "Mach 0.82 (541 mph / 871 km/h)" },
      { label: "Range", value: "2,400 nmi (4,440 km) — 727-200 Adv." },
      { label: "Passengers", value: "149–189" },
      { label: "Max takeoff weight", value: "209,500 lb (95,027 kg)" },
      { label: "Min. runway length", value: "~4,000 ft (1,219 m)" },
    ],
  },
  {
    slug: "airbus-a340",
    name: "Airbus A340",
    detail: "Airbus · Europe",
    year: 1991,
    status: "legacy",
    fact: "Four engines meant it could fly any route without ETOPS restrictions. Singapore Airlines used it for the world's longest non-stop flights — 18 hours, 45 minutes.",
    description:
      "The Airbus A340 shared its airframe, cockpit, and systems almost entirely with the twin-engine A330 — Airbus's great insight being that one design could satisfy two very different market requirements. The four CFM56 engines on the -200 and -300 variants each produced only 34,000 lbf — modest by wide-body standards — but their number guaranteed route authority: a four-engine jet was exempt from the ETOPS extended-twin operations rules that required long over-ocean diversionary planning for the A330. This gave the A340 authority to operate any route, to any destination, with no restriction.\n\nThe -500 and -600 variants switched to Rolls-Royce Trent 500 engines and offered the longest range of any airliner at the time. Singapore Airlines operated the -500 on a direct Singapore–Newark service spanning 9,534 nautical miles — taking passengers from Southeast Asia to New York in a single 18-hour-45-minute flight. The A340's commercial fate was sealed by rising fuel prices in the mid-2000s: four engines burning fuel at a comparable cost to a twin-engine jet made it economically untenable, and Airbus delivered its last in 2011.",
    specs: [
      { label: "Wingspan", value: "197 ft 10 in (60.3 m)" },
      { label: "Length", value: "208 ft 11 in (63.7 m) — A340-300" },
      { label: "Engines", value: "4× CFM56-5C4 (−200/300) or RR Trent 500 (−500/600)" },
      { label: "Thrust (each)", value: "34,000 lbf (CFM56) / 56,000 lbf (Trent 500)" },
      { label: "Cruise speed", value: "Mach 0.83 (547 mph / 880 km/h)" },
      { label: "Range", value: "16,670 km (9,000 nmi) — A340-500" },
      { label: "Passengers", value: "261–380 (varies by variant)" },
      { label: "Max takeoff weight", value: "811,300 lb (368,000 kg) — A340-600" },
    ],
  },
  {
    slug: "tupolev-tu-144",
    name: "Tupolev Tu-144",
    detail: "Tupolev · Soviet Union",
    year: 1968,
    status: "retired",
    fact: "The world's first supersonic airliner, beating Concorde to flight by three months. Known as 'Concordski', it flew Mach 2.15 — but was retired after just 55 passenger flights.",
    description:
      "The Tu-144 arrived first — first flight on December 31, 1968, three months before Concorde — and paid for that speed in almost every other dimension. Soviet aeronautical engineers, lacking the same access to advanced computational tools and wind-tunnel time as their Western counterparts, converged on a broadly similar ogival delta configuration but with significantly different engineering choices. The Tu-144's four NK-144 turbofan engines, each with afterburner, were installed in a paired arrangement under the fuselage rather than the under-wing nacelles of Concorde — a packaging that created enormous noise and vibration in the cabin.\n\nThe aircraft that entered passenger service in 1977 was effectively a rushed prototype: cabin noise required passengers to shout to be heard, fuel consumption was so high that range was limited to roughly 3,500 km, and the reliability record was poor. After a fatal crash at the 1973 Paris Air Show and another during a test flight in 1978, the passenger programme was suspended after just 55 revenue flights. The Tu-144 found a second life in the 1990s as a NASA research platform, flying supersonic test missions until 1999.",
    specs: [
      { label: "Wingspan", value: "94 ft 6 in (28.8 m)" },
      { label: "Length", value: "215 ft 6 in (65.7 m)" },
      { label: "Engines", value: "4× Kuznetsov NK-144 turbofans (with afterburner)" },
      { label: "Thrust (each)", value: "~44,090 lbf dry / 63,000 lbf with reheat" },
      { label: "Cruise speed", value: "Mach 2.15 (1,429 mph / 2,300 km/h)" },
      { label: "Service ceiling", value: "66,000 ft (20,000 m)" },
      { label: "Range", value: "~3,500 nmi (6,500 km)" },
      { label: "Passengers", value: "70–150" },
      { label: "Revenue flights", value: "55 (passenger service, 1977–1978)" },
    ],
  },
]

export const fighterJets: Aircraft[] = [
  {
    slug: "f-22-raptor",
    name: "F-22 Raptor",
    detail: "USA · Lockheed Martin",
    year: 2005,
    mach: 2.25,
    fact: "The world's pre-eminent air superiority fighter. Supercruise allows Mach 1.5+ flight without afterburner — and enemy radar sees an object the size of a marble.",
    description:
      "The F-22 Raptor was designed to a standard so exacting that no other aircraft has replicated it in the two decades since its introduction. Its stealth shaping combines edge alignment — all panel edges are swept to the same angles so radar returns arrive simultaneously and cancel — with internal weapons carriage, RAM-coated surfaces, and a low-observable engine nozzle. The result is a radar cross-section in the range of 0.0001 m², comparable to a marble.\n\nThe two Pratt & Whitney F119 engines with two-dimensional thrust-vectoring nozzles enable 'supercruise': sustained supersonic flight at Mach 1.8 without afterburner, giving the F-22 a tactical reach that afterburner-dependent fighters cannot match without burning far more fuel. At maximum thrust, it can accelerate past Mach 2 and climb to over 65,000 feet. The avionics suite fuses data from onboard and off-board sensors into a single tactical picture, allowing the Raptor to operate in near-silence — emitting so little radar that it is invisible to adversaries even as it tracks them.",
    specs: [
      { label: "Wingspan", value: "44 ft 6 in (13.56 m)" },
      { label: "Length", value: "62 ft 1 in (18.92 m)" },
      { label: "Engines", value: "2× Pratt & Whitney F119-PW-100 with 2D thrust vectoring" },
      { label: "Thrust (each)", value: "~35,000 lbf (156 kN) with afterburner" },
      { label: "Supercruise speed", value: "Mach 1.8 (no afterburner)" },
      { label: "Max speed", value: "Mach 2.25+" },
      { label: "Service ceiling", value: ">65,000 ft (19,812 m)" },
      { label: "Combat radius", value: "590 nmi (1,093 km)" },
      { label: "Radar cross-section", value: "~0.0001 m² (equivalent to a marble)" },
    ],
  },
  {
    slug: "f-35-lightning-ii",
    name: "F-35 Lightning II",
    detail: "USA · Lockheed Martin",
    year: 2015,
    mach: 1.6,
    fact: "The most expensive defence programme in history. Its helmet projects a 360° camera feed — the pilot can effectively see through the aircraft floor.",
    image: "/planes/f35.png",
    description:
      "The F-35 is the most ambitious aircraft programme ever attempted: three distinct variants — conventional take-off (A), short take-off/vertical landing (B), and carrier (C) — sharing 80% of their parts while serving the Air Force, Marine Corps, and Navy simultaneously across nine partner nations. The single F135 engine, derived from the F-22's F119 but with a larger fan, produces 43,000 lbf with afterburner — making it the most powerful fighter engine ever built.\n\nThe F-35B's vertical landing capability is the most mechanically complex aspect of the programme. A shaft-driven lift fan, located behind the cockpit and designed by Rolls-Royce, opens in the fuselage floor and generates 18,000 lbf of vertical thrust through a clutch driven by the main engine. A swivelling exhaust nozzle provides the remaining thrust vector. The Distributed Aperture System — six infrared cameras fused into a 360° sphere around the aircraft — feeds directly into the pilot's helmet visor, making the aircraft's structure literally transparent to look through. The helmet alone costs $400,000.",
    specs: [
      { label: "Wingspan", value: "35 ft 0 in (10.67 m) — F-35A" },
      { label: "Length", value: "51 ft 4 in (15.67 m) — F-35A" },
      { label: "Engine", value: "1× Pratt & Whitney F135-PW-100/400/600" },
      { label: "Thrust", value: "28,000 lbf dry / 43,000 lbf (191 kN) with afterburner" },
      { label: "Max speed", value: "Mach 1.6" },
      { label: "Range", value: "1,380 mi (2,220 km) — internal fuel" },
      { label: "Service ceiling", value: ">50,000 ft (15,240 m)" },
      { label: "Max takeoff weight", value: "70,000 lb (31,751 kg) — F-35A" },
      { label: "Variants", value: "F-35A (CTOL), F-35B (STOVL), F-35C (carrier)" },
    ],
  },
  {
    slug: "sukhoi-su-57",
    name: "Sukhoi Su-57 Felon",
    detail: "Russia · Sukhoi",
    year: 2020,
    mach: 2.0,
    fact: "Russia's first 5th-gen stealth fighter with 3D thrust-vectoring nozzles — enabling manoeuvres physically impossible for any other jet.",
    description:
      "The Sukhoi Su-57 represents Russia's most sophisticated attempt to match Western fifth-generation fighters, combining stealth shaping with the supermaneuverability that has been a hallmark of Russian fighter design since the Su-27. Its two AL-41F1 engines feature three-dimensional thrust-vectoring nozzles whose rotational axes are each canted at a different angle, enabling pitch, yaw, and roll thrust vectoring simultaneously — giving the Su-57 post-stall manoeuvrability that no other production fighter can match.\n\nThe aircraft's stealth is more limited than the F-22 or F-35, with a radar cross-section estimated between -10 and 1.0 dBm² from the front aspect — significantly larger than its Western counterparts but still a major reduction from the Su-27 it succeeds. Internal weapons bays are complemented by four external hardpoints, and the avionics suite integrates AESA radar with L-band radar arrays embedded in the wing leading edges — a system specifically designed to detect aircraft using traditional stealth coatings tuned for X-band radar.",
    specs: [
      { label: "Wingspan", value: "46 ft 3 in (14.1 m)" },
      { label: "Length", value: "69 ft 10 in (21.3 m)" },
      { label: "Engines", value: "2× Saturn AL-41F1 with 3D thrust vectoring" },
      { label: "Thrust (each)", value: "~32,000 lbf (142 kN) with afterburner" },
      { label: "Max speed", value: "Mach 2.0" },
      { label: "Service ceiling", value: "66,000 ft (20,000 m)" },
      { label: "Combat radius", value: "~1,080 nmi (2,000 km)" },
      { label: "Max takeoff weight", value: "77,162 lb (35,000 kg)" },
    ],
  },
  {
    slug: "eurofighter-typhoon",
    name: "Eurofighter Typhoon",
    detail: "UK / Germany / Italy / Spain",
    year: 2003,
    mach: 2.0,
    fact: "A four-nation collaboration. Its unstable canard-delta design generates extreme lift, making it one of the most agile fighters ever built.",
    description:
      "The Eurofighter Typhoon was designed from the outset to be aerodynamically unstable — meaning the aircraft would depart controlled flight immediately without continuous computer intervention. This deliberate instability is the source of its exceptional agility: the fly-by-wire computers fire the control surfaces up to 40 times per second to maintain equilibrium, and within those commands the pilot's inputs translate into extreme manoeuvrability that a stable design physically cannot match.\n\nThe close-coupled delta-canard configuration places small forward fins (canards) ahead of the main delta wing. These canards generate powerful vortices that energise the airflow over the main wing, delaying stall to extreme angles of attack. The two Eurojet EJ200 engines, each producing 20,250 lbf with afterburner, give the Typhoon a thrust-to-weight ratio exceeding 1.07 at typical combat weight — meaning it can accelerate while climbing vertically. The aircraft can also supercruise at Mach 1.1–1.2 in military power, without resorting to fuel-hungry afterburner.",
    specs: [
      { label: "Wingspan", value: "35 ft 11 in (10.95 m)" },
      { label: "Length", value: "52 ft 4 in (15.96 m)" },
      { label: "Engines", value: "2× Eurojet EJ200 afterburning turbofans" },
      { label: "Thrust (each)", value: "20,250 lbf (90 kN) with afterburner" },
      { label: "Max speed", value: "Mach 2.0 (1,322 mph / 2,125 km/h)" },
      { label: "Service ceiling", value: "65,000 ft (19,812 m)" },
      { label: "Combat radius", value: "~1,000 nmi (1,852 km)" },
      { label: "Max takeoff weight", value: "51,809 lb (23,500 kg)" },
      { label: "Supercruise", value: "Mach 1.1–1.2 (no afterburner)" },
    ],
  },
  {
    slug: "dassault-rafale",
    name: "Dassault Rafale",
    detail: "France · Dassault Aviation",
    year: 2001,
    mach: 1.8,
    fact: "France's omnirole 4.5-gen fighter. The SPECTRA EW suite can jam incoming missiles and generate false radar signatures autonomously.",
    description:
      "Dassault's Rafale was born from France's decision to leave the Eurofighter programme in 1985, preferring full national control over a uniquely French multirole aircraft. Where the Typhoon was optimised for air superiority, the Rafale was designed from the start for 'omnirole' operations: the same jet, the same mission, capable of air-to-air combat, precision strike, carrier operations, and nuclear delivery within a single sortie without reconfiguration.\n\nThe SPECTRA electronic warfare system is the aircraft's most advanced feature. It combines laser missile approach warning, radar warning receivers, a Doppler radar jammer, and the ability to generate deceptive radar signatures — effectively creating a false radar image of a different aircraft at a different location. The RBE2-AA active electronically scanned array radar maps terrain and tracks air targets simultaneously. The delta-canard aerodynamics, combined with the 70% composite airframe, give the Rafale a short-field performance and approach speed compatible with French carriers despite weighing nearly 25,000 kg at max weight.",
    specs: [
      { label: "Wingspan", value: "35 ft 9 in (10.9 m)" },
      { label: "Length", value: "50 ft 2 in (15.3 m)" },
      { label: "Engines", value: "2× Snecma M88-2 afterburning turbofans" },
      { label: "Thrust (each)", value: "11,250 lbf dry / 17,000 lbf (75.6 kN) with afterburner" },
      { label: "Max speed", value: "Mach 1.8 (1,185 mph / 1,912 km/h)" },
      { label: "Service ceiling", value: "50,000 ft (15,240 m)" },
      { label: "Combat radius", value: "1,000 nmi (1,850 km) — hi-lo-hi" },
      { label: "Max takeoff weight", value: "54,013 lb (24,500 kg)" },
      { label: "Composite content", value: "~70% of airframe surface" },
    ],
  },
  {
    slug: "fa-18-super-hornet",
    name: "F/A-18E Super Hornet",
    detail: "USA · Boeing",
    year: 1999,
    mach: 1.8,
    fact: "The US Navy's primary strike fighter — it can refuel allied jets mid-air, then arrest onto a carrier deck at 150 mph using a tailhook.",
    description:
      "The F/A-18E/F Super Hornet is a significant redesign of the original Hornet, not merely a stretched version: the fuselage is 25% larger, the wing area is 25% greater, and the two GE F414 engines produce 35% more thrust than the F404s in the original. These changes give the Super Hornet a 40% increase in range and a 25% increase in payload compared to its predecessor, while retaining full carrier compatibility.\n\nThe aircraft's 'legacy hornet' lineage gives it a design philosophy centred on adaptability. The Super Hornet can carry the AN/ASQ-228 Advanced Targeting Forward-Looking Infrared pod, the ALQ-214 IDECM jamming system, and the Integrated Defense Electronic Countermeasures suite — making it one of the most electronically versatile fighters in service. In the 'Growler' variant (EA-18G), all air-to-air weapons are replaced with jamming pods, turning the airframe into a dedicated electronic warfare aircraft. The Super Hornet also carries a centreline hose-and-drogue refuelling pod, allowing it to refuel other aircraft mid-mission before recovering to the carrier.",
    specs: [
      { label: "Wingspan", value: "44 ft 9 in (13.62 m)" },
      { label: "Length", value: "60 ft 1 in (18.31 m)" },
      { label: "Engines", value: "2× General Electric F414-GE-400 turbofans" },
      { label: "Thrust (each)", value: "22,000 lbf (97.9 kN) with afterburner" },
      { label: "Max speed", value: "Mach 1.8 (1,190 mph / 1,915 km/h)" },
      { label: "Service ceiling", value: "50,000 ft (15,240 m)" },
      { label: "Combat radius", value: "449 nmi (832 km)" },
      { label: "Max takeoff weight", value: "66,000 lb (29,937 kg)" },
      { label: "Landing speed (carrier)", value: "~150 mph (241 km/h)" },
    ],
  },
  {
    slug: "sr-71-blackbird",
    name: "SR-71 Blackbird",
    detail: "USA · Lockheed Skunk Works",
    year: 1966,
    mach: 3.3,
    status: "retired",
    fact: "The fastest air-breathing manned aircraft ever built. At Mach 3.3 it outran every missile ever fired at it — the standard evasive manoeuvre was simply to accelerate.",
    description:
      "The SR-71 Blackbird was so fast that the engineers who designed it had to invent new materials, fuels, and manufacturing methods simply to keep it from destroying itself. Over 90% of the airframe was titanium — a metal the US had to purchase covertly from the Soviet Union through front companies, since it was the world's principal supplier. The aircraft expanded several inches in length from the heat of supersonic flight, which is why the fuel tanks leaked on the ground: they were designed with gaps that only sealed shut when the airframe reached operating temperature.\n\nThe Pratt & Whitney J58 engines were unique in aviation history: above Mach 3, the intake contributed 54% of total thrust, the exhaust ejector nozzle 28.4%, and the engine itself only 17.6%. The aircraft was effectively a ramjet at cruise speed, with a turbojet core simply acting as a pump and ignitor. The crew wore full pressure suits similar to astronauts. Every reconnaissance mission flown over denied territory ended the same way: the SR-71 simply accelerated to a speed no surface-to-air missile could match.",
    specs: [
      { label: "Wingspan", value: "55 ft 7 in (16.94 m)" },
      { label: "Length", value: "107 ft 5 in (32.74 m)" },
      { label: "Engines", value: "2× Pratt & Whitney J58-P-4 turboramjets" },
      { label: "Thrust (each)", value: "32,500 lbf (144.6 kN) with afterburner" },
      { label: "Max speed", value: "Mach 3.3+ (2,200+ mph / 3,540+ km/h)" },
      { label: "Service ceiling", value: "85,000 ft (25,908 m)" },
      { label: "Range", value: "3,200 nmi (5,926 km)" },
      { label: "Skin temperature at cruise", value: "316°C (nose) / up to 593°C (engine nacelles)" },
      { label: "Airframe material", value: ">90% titanium alloy" },
    ],
  },
  {
    slug: "f-14-tomcat",
    name: "F-14 Tomcat",
    detail: "USA · Grumman",
    year: 1974,
    mach: 2.34,
    status: "retired",
    fact: "The variable-sweep wing icon of Top Gun. Its AWG-9 radar could track 24 targets simultaneously and engage 6 at once — unmatched in 1974.",
    description:
      "The F-14 Tomcat was designed around a single requirement: kill Soviet bombers before they could launch their cruise missiles at a carrier battle group. The answer was the AIM-54 Phoenix missile, which could engage targets 100 miles away, and the Hughes AWG-9 radar that could track 24 of them simultaneously and fire on 6 at once — a combination that remained unmatched for a generation.\n\nThe variable-geometry wing was the key to making a carrier aircraft that was both fast and slow. Wings fully swept to 68° gave supersonic dash performance; wings spread to 20° gave the low approach speed needed to land on a carrier deck without overstressing the arresting gear. The wings moved automatically, governed by the aircraft's air data computer, without pilot input during normal flight. Grumman's 'turkey feathers' — interlocking afterburner nozzle petals — became the visual signature of the aircraft. Iran remains the only foreign operator of the F-14; their aircraft, sold before the 1979 revolution, are some of the last in existence.",
    specs: [
      { label: "Wingspan", value: "38 ft (swept) to 64 ft (extended) — 11.6 m / 19.5 m" },
      { label: "Length", value: "62 ft 8 in (19.1 m)" },
      { label: "Engines", value: "2× GE F110-GE-400 (F-14B/D) afterburning turbofans" },
      { label: "Thrust (each)", value: "27,600 lbf (122.8 kN) dry / further with AB" },
      { label: "Max speed", value: "Mach 2.34 (1,544 mph / 2,485 km/h)" },
      { label: "Service ceiling", value: "50,000 ft (15,240 m)" },
      { label: "Radar", value: "Hughes AWG-9: tracks 24 targets, engages 6 simultaneously" },
      { label: "Max missile range (AIM-54)", value: "100+ nmi (185+ km)" },
      { label: "Max takeoff weight", value: "74,350 lb (33,724 kg)" },
    ],
  },
  {
    slug: "f-15-eagle",
    name: "F-15 Eagle",
    detail: "USA · McDonnell Douglas",
    year: 1976,
    mach: 2.5,
    fact: "Undefeated in air-to-air combat with over 100 kills and zero losses. Its thrust-to-weight ratio exceeds 1 — it can accelerate straight up.",
    description:
      "The F-15 Eagle was conceived in the wake of the Vietnam War, where US fighters with multi-role versatility had proven inadequate against the simpler, lighter MiG-21. The lesson McDonnell Douglas drew was that air superiority required a dedicated single-purpose aircraft: no ground attack, no compromises, no weight penalties. The result was a jet with a thrust-to-weight ratio exceeding 1.0 at typical combat weight — meaning it could accelerate while pointing straight up.\n\nThe Eagle's design philosophy permeates every system. The 608 sq ft wing — enormous for a fighter — provides exceptional energy retention in high-G manoeuvres. The twin Pratt & Whitney F100 engines in closely-spaced nacelles minimise interference drag while providing redundancy. The APG-63 pulse-Doppler radar was the first capable of detecting and tracking low-flying aircraft against ground clutter — a capability that would define subsequent fighter radar requirements globally. The F-15's combat record across the Israeli Air Force, USAF, and Royal Saudi Air Force stands at over 100 confirmed kills against zero air-to-air losses, a record unmatched by any other aircraft.",
    specs: [
      { label: "Wingspan", value: "42 ft 10 in (13.05 m)" },
      { label: "Length", value: "63 ft 9 in (19.43 m)" },
      { label: "Engines", value: "2× Pratt & Whitney F100-PW-100/220 afterburning turbofans" },
      { label: "Thrust (each)", value: "23,830 lbf dry / 25,000 lbf (111.2 kN) with AB" },
      { label: "Max speed", value: "Mach 2.5+ (1,650+ mph / 2,655+ km/h)" },
      { label: "Service ceiling", value: "65,000 ft (19,812 m)" },
      { label: "Combat radius", value: "1,061 nmi (1,965 km)" },
      { label: "Max takeoff weight", value: "68,000 lb (30,845 kg)" },
      { label: "Air-to-air combat record", value: "100+ kills / 0 losses" },
    ],
  },
  {
    slug: "f-16-fighting-falcon",
    name: "F-16 Fighting Falcon",
    detail: "USA · General Dynamics",
    year: 1978,
    mach: 2.05,
    fact: "The first production fly-by-wire fighter. Intentionally aerodynamically unstable — a computer fires the control surfaces 40 times per second to keep it airborne.",
    description:
      "The F-16 was born from a radical idea in the 1970s 'Lightweight Fighter' competition: that a small, cheap, highly agile aircraft specifically designed for visual-range dogfighting could outperform the larger, more expensive fighters it would accompany. General Dynamics designer Harry Hillaker took the concept further than anyone expected, building deliberate aerodynamic instability into the design to maximise agility — making it the first production aircraft that could not be flown without a flight control computer.\n\nThe fly-by-wire system was so new that the prototype had no manual backup: if the computers failed, the aircraft departed controlled flight. In the cockpit, the traditional centre stick was replaced by a side-mounted force-sensing controller — the pilot's hand barely moved, but the computers translated that force into control surface commands 40 times per second. The single F100 engine and blended wing-body design — where the fuselage itself generates lift — kept the aircraft extraordinarily light. The F-16's 9-G limit was not a structural compromise but an intentional maximum set by human physiology: it was the first fighter designed specifically to pull the maximum G-force a pilot can survive.",
    specs: [
      { label: "Wingspan", value: "31 ft 0 in (9.45 m)" },
      { label: "Length", value: "49 ft 5 in (15.06 m)" },
      { label: "Engine", value: "1× P&W F100-PW-220 or GE F110-GE-100 afterburning turbofan" },
      { label: "Thrust", value: "23,000–29,000 lbf (102–129 kN) with afterburner (varies)" },
      { label: "Max speed", value: "Mach 2.05 (1,350 mph / 2,175 km/h)" },
      { label: "Service ceiling", value: ">50,000 ft (15,240 m)" },
      { label: "Combat radius", value: "295–340 nmi (546–630 km) — typical hi-lo-hi" },
      { label: "Max G-load", value: "9-G (structural limit = human physiological limit)" },
      { label: "Max takeoff weight", value: "42,300 lb (19,187 kg)" },
    ],
  },
  {
    slug: "f-117-nighthawk",
    name: "F-117 Nighthawk",
    detail: "USA · Lockheed Skunk Works",
    year: 1983,
    mach: 0.92,
    status: "retired",
    fact: "The world's first operational stealth aircraft. Its faceted angular skin was designed by a computer to scatter radar — making an aircraft the size of a fighter invisible.",
    description:
      "The F-117 Nighthawk's design was driven not by aerodynamics but by mathematics. In the early 1970s, Lockheed Skunk Works engineer Denys Overholser applied a 1960s Soviet electromagnetic scattering theory by Pyotr Ufimtsev to calculate the radar reflection of arbitrary flat-faceted shapes. The result was that a surface composed entirely of flat panels at specific angles would scatter incoming radar energy away from its source — making the aircraft nearly invisible to enemy radar, at the cost of being aerodynamically atrocious.\n\nTo actually fly the thing, Lockheed's engineers had to borrow the fly-by-wire computers from the F-16 and then reprogram them entirely. The F-117 was so aerodynamically unstable that without continuous computer correction, it would depart controlled flight in milliseconds. The faceted surfaces were coated in radar-absorbent material that reduced residual reflections. The aircraft had no afterburner — its GE F404 engines were de-tuned to minimise infrared signature — and flew subsonic missions exclusively. It was officially retired in 2008, but reports in subsequent years have documented F-117s continuing flight operations under unknown programmes.",
    specs: [
      { label: "Wingspan", value: "43 ft 4 in (13.2 m)" },
      { label: "Length", value: "65 ft 11 in (20.08 m)" },
      { label: "Engines", value: "2× General Electric F404-GE-F1D2 (no afterburner)" },
      { label: "Thrust (each)", value: "10,800 lbf (48 kN) dry" },
      { label: "Max speed", value: "Mach 0.92 (617 mph / 993 km/h)" },
      { label: "Service ceiling", value: "45,000 ft (13,716 m)" },
      { label: "Range", value: "930 nmi (1,722 km)" },
      { label: "Max takeoff weight", value: "52,500 lb (23,814 kg)" },
      { label: "Radar cross-section", value: "~0.001 m² (estimated)" },
    ],
  },
  {
    slug: "mig-29-fulcrum",
    name: "MiG-29 Fulcrum",
    detail: "Russia · Mikoyan",
    year: 1983,
    mach: 2.25,
    fact: "Its helmet-mounted sight lets pilots fire missiles simply by looking at a target — a revelation that shocked Western intelligence when first uncovered.",
    description:
      "The MiG-29 was designed as a direct counter to the F-15 and F-16, matching Western fighters in both the high-altitude, high-speed regime and the close-in dogfight. Its twin RD-33 engines and twin leading-edge root extensions (LERXes) that generate powerful vortices over the wing give it exceptional instantaneous turn rate. The variable-geometry intakes use louvers that close during ground operations to prevent Foreign Object Damage, with auxiliary inlets opening above the intakes — an elegant solution to carrier and rough-field operations.\n\nThe IRST (Infrared Search and Track) sensor mounted ahead of the cockpit can detect jet exhausts at 45 km range in a passive mode that emits nothing detectable — allowing the MiG-29 to engage targets without activating its radar. Coupled to the helmet-mounted sight that could cue R-73 'Archer' missiles to targets 60° off the aircraft's nose, this gave MiG-29 pilots a within-visual-range engagement capability that Western pilots could not match until JHMCS systems were fielded in the late 1990s. When German pilots finally flew captured East German MiG-29s against NATO aircraft post-reunification, the results were sobering.",
    specs: [
      { label: "Wingspan", value: "37 ft 3 in (11.36 m)" },
      { label: "Length", value: "56 ft 10 in (17.32 m)" },
      { label: "Engines", value: "2× Klimov RD-33 afterburning turbofans" },
      { label: "Thrust (each)", value: "18,300 lbf (81.4 kN) with afterburner" },
      { label: "Max speed", value: "Mach 2.25 (1,519 mph / 2,445 km/h)" },
      { label: "Service ceiling", value: "59,055 ft (18,000 m)" },
      { label: "Combat radius", value: "400 nmi (740 km)" },
      { label: "Max takeoff weight", value: "40,785 lb (18,500 kg)" },
      { label: "Helmet-mounted sight", value: "R-73 missiles cued up to 60° off boresight" },
    ],
  },
  {
    slug: "saab-jas-39-gripen",
    name: "Saab JAS 39 Gripen",
    detail: "Sweden · Saab",
    year: 1997,
    mach: 2.0,
    fact: "Designed to land on public roads and be rearmed by a five-man conscript crew in under 10 minutes — the most cost-effective 4th-gen multirole fighter in operation.",
    description:
      "The JAS 39 Gripen was shaped entirely by Sweden's unique defence doctrine: total defence, which assumed a Soviet invasion might overrun or destroy conventional air bases, requiring fighter operations from dispersed road strips and forest clearings. The aircraft had to be maintainable by a team of five conscripts without specialist equipment, refuelled and rearmed within 10 minutes of landing, and able to take off and land safely on a 9-metre-wide road.\n\nThese operational constraints produced an aircraft optimised for sortie rate over raw performance. The single Volvo RM12 engine (a licence-built GE F404 derivative) was chosen partly because removing it for maintenance requires only a single technician. The fly-by-wire system, developed by Saab, includes automatic recovery modes that can regain controlled flight from a spin — critical for single-engine operation over difficult terrain. The delta-canard configuration provides excellent short-field performance. In NATO exercises, Gripen pilots flying air combat manoeuvring against Typhoons and Rafales have consistently achieved competitive kill ratios, earning the aircraft the designation of most cost-effective multirole fighter in the Western inventory.",
    specs: [
      { label: "Wingspan", value: "27 ft 7 in (8.4 m)" },
      { label: "Length", value: "46 ft 3 in (14.1 m)" },
      { label: "Engine", value: "1× Volvo RM12 (GE F404 derivative)" },
      { label: "Thrust", value: "18,100 lbf (80.5 kN) with afterburner" },
      { label: "Max speed", value: "Mach 2.0 (1,322 mph / 2,126 km/h)" },
      { label: "Service ceiling", value: ">50,000 ft (15,240 m)" },
      { label: "Combat radius", value: "500+ nmi (926+ km)" },
      { label: "Max takeoff weight", value: "31,000 lb (14,000 kg)" },
      { label: "Min. road strip requirement", value: "9 m wide, 800 m long" },
    ],
  },
]

export const engines: Aircraft[] = [
  {
    slug: "ge90-115b",
    name: "GE90-115B",
    detail: "GE Aviation · High-bypass turbofan",
    year: 1995,
    fact: "The world's most powerful commercial jet engine at 115,000 lbf of thrust — it could lift a fully loaded 747 on its own.",
    description:
      "The GE90 family was GE Aviation's clean-sheet response to the Boeing 777 programme, and the -115B variant represented a leap beyond anything previously certified for commercial use. Its 22 fan blades are carbon-fibre composites — each over four feet long and curved like an eagle's wing — providing double the strength of titanium at one-third the weight. The fan case is a single composite hoop rather than a segmented metal assembly, reducing weight further while containing any blade release event.\n\nAt 128 inches in diameter, the GE90-115B fan is wider than a Boeing 737's fuselage. During certification ground testing, the engine produced 127,900 lbf — a world record that stood for over a decade. At 115,000 lbf of rated thrust, each engine provides more than the combined thrust of all four engines on an early Boeing 747. The 42:1 overall pressure ratio — versus the 30:1 of contemporary competitors — means the combustor operates at temperatures requiring single-crystal turbine blades cooled by air circulating through internal channels no thicker than a human hair.",
    specs: [
      { label: "Type", value: "High-bypass turbofan" },
      { label: "Thrust", value: "115,000 lbf (512 kN) rated" },
      { label: "Fan diameter", value: "128 in (325 cm)" },
      { label: "Bypass ratio", value: "9:1" },
      { label: "Overall pressure ratio", value: "42:1" },
      { label: "Fan blades", value: "22 carbon-fibre composite blades" },
      { label: "Aircraft", value: "Boeing 777 (exclusive)" },
      { label: "Weight", value: "20,400 lb (9,253 kg)" },
    ],
  },
  {
    slug: "rolls-royce-trent-xwb",
    name: "Trent XWB-97",
    detail: "Rolls-Royce · High-bypass turbofan",
    year: 2014,
    fact: "The world's most efficient large aero engine. Powers the A350-1000 and burns 25% less fuel per seat than the jets it replaces.",
    description:
      "The Trent XWB ('Extra Wide Body') was developed concurrently with the Airbus A350 it exclusively powers, making it the first major commercial engine in decades designed for only one airframe. This single-customer relationship allowed Rolls-Royce and Airbus to co-optimise the engine and nacelle in ways that would be impossible with competing installations — the intake, fan cowl, and thrust reverser are all tuned to the A350's specific nacelle geometry.\n\nThe three-spool architecture unique to Rolls-Royce — with three separate rotating assemblies rather than the two used by GE and Pratt & Whitney — allows each spool to operate at its aerodynamically optimal speed. The XWB-97's 61:1 overall pressure ratio is the highest of any large commercial engine, meaning fuel burns more completely and the thermodynamic cycle extracts more work per kilogram of air processed. The 118-inch titanium fan and advanced wide-chord blades contribute to an overall efficiency that gives the A350-1000 its 9,700 nmi ultra-long-range capability without refuelling.",
    specs: [
      { label: "Type", value: "High-bypass turbofan (three-spool)" },
      { label: "Thrust", value: "97,000 lbf (431 kN)" },
      { label: "Fan diameter", value: "118 in (300 cm)" },
      { label: "Bypass ratio", value: "9.3:1" },
      { label: "Overall pressure ratio", value: "61:1 (highest of any large commercial engine)" },
      { label: "Aircraft", value: "Airbus A350-1000" },
      { label: "Fuel saving", value: "25% vs. previous-generation jets" },
    ],
  },
  {
    slug: "cfm-leap-1a",
    name: "CFM LEAP-1A",
    detail: "CFM International · High-bypass turbofan",
    year: 2016,
    fact: "The most ordered jet engine in history. Its 3D-woven carbon-fibre fan blades and ceramic matrix combustor deliver a 15% fuel saving over the CFM56.",
    description:
      "The CFM LEAP (Leading Edge Aviation Propulsion) is the joint product of GE Aviation and Safran Aircraft Engines, successors to the CFM56 partnership that produced the best-selling jet engine in history. The LEAP carries forward that partnership's commercial dominance while leaping beyond it technically: where the CFM56 used aluminium fan blades, the LEAP uses 3D-woven carbon-fibre blades formed by a process originally developed for rocket motor cases.\n\nThe combustor lining is ceramic matrix composite — the first commercial use of CMC in a hot-section component. CMC can withstand temperatures 500°F higher than the nickel superalloys it replaces, meaning the combustor can run hotter and more efficiently without additional cooling air. Less cooling air means more air goes through the combustion process, improving efficiency further. The resulting bypass ratio of 11:1, versus the CFM56's 5.9:1, dramatically reduces jet noise. Three LEAP variants serve the A320neo (LEAP-1A), 737 MAX (LEAP-1B), and COMAC C919 (LEAP-1C), collectively representing over 20,000 orders.",
    specs: [
      { label: "Type", value: "High-bypass turbofan" },
      { label: "Thrust range", value: "22,000–32,900 lbf (98–146 kN)" },
      { label: "Fan diameter", value: "78 in (198 cm)" },
      { label: "Bypass ratio", value: "11:1" },
      { label: "Fan material", value: "3D-woven carbon-fibre composite" },
      { label: "Combustor liner", value: "Ceramic matrix composite (CMC)" },
      { label: "Aircraft", value: "A320neo (1A), 737 MAX (1B), COMAC C919 (1C)" },
      { label: "Fuel saving vs CFM56", value: "15%" },
    ],
  },
  {
    slug: "ge9x",
    name: "GE9X-105B1A",
    detail: "GE Aviation · High-bypass turbofan",
    year: 2018,
    fact: "Powers the Boeing 777X with the largest fan diameter of any commercial engine at 134 inches — wider than the fuselage of a 737. During testing it exceeded 134,300 lbf.",
    description:
      "The GE9X was designed specifically for the Boeing 777X, building on the GE90's heritage but incorporating three decades of materials science and aerodynamic advances. Where the GE90's fan used 22 blades, the GE9X achieves comparable thrust from just 16 — each blade wider and more aerodynamically efficient, fabricated from next-generation carbon-fibre composites. The 134-inch fan diameter creates the widest engine ever certified for commercial use.\n\nThe combustor is ceramic matrix composite throughout — an advance beyond the LEAP's partial CMC liner — allowing turbine inlet temperatures that would destroy earlier nickel superalloy components. The fourth-generation advanced high-pressure compressor achieves a pressure ratio of 60:1 in the core alone. Combined with the 10:1 bypass ratio, the overall thermodynamic cycle delivers 10% better specific fuel consumption than the GE90 it conceptually descends from. In November 2017, during sea-level test runs at Peebles, Ohio, the GE9X reached 134,300 lbf — setting a new world thrust record for a commercial engine.",
    specs: [
      { label: "Type", value: "High-bypass turbofan" },
      { label: "Thrust", value: "105,000 lbf (467 kN) rated / 134,300 lbf (peak test)" },
      { label: "Fan diameter", value: "134 in (340 cm) — largest commercial engine fan" },
      { label: "Fan blades", value: "16 (vs 22 on GE90)" },
      { label: "Bypass ratio", value: "10:1" },
      { label: "Core pressure ratio", value: "60:1" },
      { label: "Combustor material", value: "Full ceramic matrix composite (CMC)" },
      { label: "Aircraft", value: "Boeing 777X (777-8 and 777-9)" },
      { label: "Fuel saving vs GE90", value: "10%" },
    ],
  },
  {
    slug: "pw-f135",
    name: "Pratt & Whitney F135",
    detail: "Pratt & Whitney · Low-bypass afterburning turbofan",
    year: 2006,
    fact: "The most powerful fighter engine ever built at 43,000 lbf with afterburner. Its lift-fan variant enables the F-35B to hover and land vertically.",
    description:
      "The F135 is derived from the F-22's F119 engine but with a larger fan and higher bypass ratio, optimising it for the F-35's different performance requirements — more subsonic efficiency and range, slightly less supersonic dash. The three variants (F135-PW-100 for the F-35A, -400 for the F-35C, and -600 for the F-35B) share a common core but differ in their interface with the airframe.\n\nThe F-35B's F135-600 variant is the most complex, mechanically coupling to a Rolls-Royce-designed lift fan via a carbon-fibre drive shaft with a clutch mechanism. When the pilot transitions to STOVL mode, the fan door in the fuselage floor opens, the clutch engages, and the lift fan begins spinning — taking over 20,000 lbf of downward thrust from the main engine, which simultaneously swivels its thrust-vectoring three-bearing swivel nozzle rearward and downward. Two roll-post nozzles near the wingtips provide lateral control. The system transitions from wingborne flight to fanborne hover in under 10 seconds.",
    specs: [
      { label: "Type", value: "Low-bypass augmented turbofan" },
      { label: "Thrust (dry)", value: "28,000 lbf (125 kN)" },
      { label: "Thrust (afterburner)", value: "43,000 lbf (191 kN)" },
      { label: "Bypass ratio", value: "0.57:1" },
      { label: "Lift fan thrust (F-35B)", value: "18,000 lbf (80 kN) — Rolls-Royce designed" },
      { label: "Aircraft", value: "F-35A/B/C Lightning II" },
      { label: "Derived from", value: "Pratt & Whitney F119 (F-22 engine)" },
    ],
  },
  {
    slug: "olympus-593",
    name: "Olympus 593",
    detail: "Rolls-Royce / Snecma · Turbojet",
    year: 1966,
    status: "retired",
    fact: "Concorde's engine. At Mach 2 the intake air reached 127°C before combustion even began — the engine itself became a heat exchanger.",
    description:
      "The Olympus 593 was a development of the Bristol Siddeley Olympus turbojet that had powered the Vulcan bomber, but scaled, refined, and equipped with afterburner (called 'reheat' in British terminology) for supersonic flight. The most extraordinary challenge its designers faced was thermodynamic: at Mach 2, the compression of the intake air alone raised it to 127°C. The engineers had to design a turbofan whose compressor stages accepted pre-heated air — conditions that would cause compressor stall in most conventional engines.\n\nThe intake itself was as important as the engine. A pair of variable-geometry ramps in each engine intake automatically adjusted to manage the shock wave system of supersonic flight, decelerating the airflow from Mach 2 to subsonic speed before it reached the compressor face. This shock management recovered roughly 60% of the total thrust — more than the engine core itself at cruise. The reheat system was used only for takeoff and the transonic acceleration to Mach 1.7; at cruise, the engine ran dry, making Concorde the only aircraft to sustain commercial supersonic cruise on turbojet power alone.",
    specs: [
      { label: "Type", value: "Afterburning turbojet (two-spool)" },
      { label: "Thrust (dry)", value: "31,000 lbf (137.9 kN)" },
      { label: "Thrust (reheat)", value: "38,050 lbf (169.3 kN)" },
      { label: "Overall pressure ratio", value: "15.5:1" },
      { label: "Intake air temperature at Mach 2", value: "127°C" },
      { label: "Aircraft", value: "Concorde" },
      { label: "Intake type", value: "Variable-geometry ramps (manage Mach 2 shockwave)" },
      { label: "Reheat used for", value: "Takeoff + transonic acceleration only" },
    ],
  },
  {
    slug: "ge-f110",
    name: "GE F110-GE-129",
    detail: "GE Aviation · Low-bypass afterburning turbofan",
    year: 1984,
    fact: "Produces 29,500 lbf with afterburner in the F-16 Block 50 — giving a thrust-to-weight ratio greater than 1, enabling a vertical climb from a standing start.",
    description:
      "The GE F110 was born from a US Air Force initiative to create a second source of engines for the F-16, ending Pratt & Whitney's monopoly and forcing competition. GE based it on the F101 core from the B-1 Lancer bomber — a mature, reliable design that could be scaled and adapted faster than developing a new core from scratch. The strategy worked: the F110 competed directly against Pratt & Whitney's F100, and today it powers roughly half of all production F-16s.\n\nThe -GE-129 variant produces 29,500 lbf with afterburner, compared to the original F110-100's 28,984 lbf and the F100-PW-200's 23,830 lbf. This thrust increase gave the F-16 Block 50/52 a thrust-to-weight ratio exceeding 1:1, making sustained vertical flight possible. The engine's modular construction allows line maintenance to replace any section without removing the entire powerplant — critical for the rapid turnaround time that defines F-16 operations. GE subsequently scaled the F110 core further to produce the F118 for the B-2 Spirit stealth bomber.",
    specs: [
      { label: "Type", value: "Low-bypass augmented turbofan" },
      { label: "Thrust (dry)", value: "~17,155 lbf (76.3 kN)" },
      { label: "Thrust (afterburner)", value: "29,500 lbf (131.2 kN)" },
      { label: "Bypass ratio", value: "0.87:1" },
      { label: "Fan diameter", value: "46.5 in (118 cm)" },
      { label: "Aircraft", value: "F-16 Block 50/52, F-15K/SG" },
      { label: "Derived from", value: "GE F101 (B-1 Lancer bomber engine core)" },
      { label: "Thrust-to-weight (F-16 Block 50)", value: ">1.0 at typical combat weight" },
    ],
  },
]
